services:
  search.record:
    class: TrackerBundle\Services\SearchRecordByIdUseCase
    arguments: ["@doctrine.orm.entity_manager"]
  search.post:
    class: TrackerBundle\Services\SearchPostByIdUseCase
    arguments: ["@doctrine.orm.entity_manager"]