services:
  tracker_record.create:
    class: TrackerBundle\Services\CreateRecordUseCase
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@event_dispatcher"
  tracker_record.list:
    class: TrackerBundle\Services\ListRecords
    arguments:
      - "@doctrine.orm.entity_manager"
  tracker_record.search.by_id:
    class: TrackerBundle\Services\SearchRecordById
    arguments:
      - "@doctrine.orm.entity_manager"

  tracker_post.records.list:
    class: TrackerBundle\Services\ListPostRecords
    arguments:
      - "@doctrine.orm.entity_manager"
  tracker_post.list:
    class: TrackerBundle\Services\ListPosts
    arguments:
      - "@doctrine.orm.entity_manager"
  tracker_post.search.by_id:
    class: TrackerBundle\Services\SearchPostById
    arguments:
      - "@doctrine.orm.entity_manager"
  tracker_post.search.by_slug:
    class: TrackerBundle\Services\SearchPostBySlug
    arguments:
      - "@doctrine.orm.entity_manager"
