# Blog routes
blog_list:
    path:     /blog
    defaults: { _controller: BlogBundle:Blog:blog }

post:
    path:     /blog/{postSlug}
    defaults: { _controller: BlogBundle:Blog:post }

# Blog Admin routes
admin_list:
    path:     /admin
    defaults: { _controller: BlogBundle:Admin:admin }

post_create:
    path:     /admin/create
    defaults: { _controller: BlogBundle:Admin:createPost }

post_edit:
    path:     /admin/edit/{postSlug}
    defaults: { _controller: BlogBundle:Admin:editPost }

