# Blog services
services:
  blog_post.create:
    class: BlogBundle\Services\CreatePostUseCase
    arguments:
      - "@doctrine.orm.entity_manager"
  blog_post.list:
    class: BlogBundle\Services\ListPosts
    arguments:
      - "@doctrine.orm.entity_manager"
  blog_post.search.by_slug:
    class: BlogBundle\Services\SearchPostBySlug
    arguments:
      - "@doctrine.orm.entity_manager"
