BlogBundle\Entity\Post:
  type: entity
  repositoryClass: BlogBundle\Repository\DoctrinePostRepository
  table: post
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    slug:
      type: string
      length: 100
    title:
      type: string
      length: 100
    description:
      type: text
    published:
      type: boolean
      default: false
    createdAt:
      type: datetime
      column: created_at
